// This file is auto-generated by: pnpm db:types
// Run: supabase gen types typescript --local > packages/types/src/supabase.ts
// Do not edit manually — regenerate after every migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          subdomain: string;
          api_key: string;
        };
        Insert: {
          id?: string;
          name: string;
          subdomain: string;
          api_key?: string;
        };
        Update: {
          id?: string;
          name?: string;
          subdomain?: string;
          api_key?: string;
        };
        Relationships: [];
      };
      posts: {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          slug: string;
          content: Json;
          status: string;
          seo_metadata: Json | null;
          featured: boolean;
          cover_image: string | null;
          excerpt: string | null;
          category: string | null;
          author: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          slug: string;
          content?: Json;
          status?: string;
          seo_metadata?: Json | null;
          featured?: boolean;
          cover_image?: string | null;
          excerpt?: string | null;
          category?: string | null;
          author?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          title?: string;
          slug?: string;
          content?: Json;
          status?: string;
          seo_metadata?: Json | null;
          featured?: boolean;
          cover_image?: string | null;
          excerpt?: string | null;
          category?: string | null;
          author?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'posts_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      media: {
        Row: {
          id: string;
          tenant_id: string;
          url: string;
          alt_text: string | null;
          metadata: Json | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          url: string;
          alt_text?: string | null;
          metadata?: Json | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          url?: string;
          alt_text?: string | null;
          metadata?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: 'media_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      settings: {
        Row: {
          tenant_id: string;
          theme_config: Json;
          seo_metadata: Json;
        };
        Insert: {
          tenant_id: string;
          theme_config?: Json;
          seo_metadata?: Json;
        };
        Update: {
          tenant_id?: string;
          theme_config?: Json;
          seo_metadata?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'settings_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: true;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
      user_tenant_map: {
        Row: {
          user_id: string;
          tenant_id: string;
        };
        Insert: {
          user_id: string;
          tenant_id: string;
        };
        Update: {
          user_id?: string;
          tenant_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_tenant_map_tenant_id_fkey';
            columns: ['tenant_id'];
            isOneToOne: false;
            referencedRelation: 'tenants';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
